[markup.goldmark.renderer]
unsafe = true 

[module]
	[[module.imports]]
		path = "github.com/vyberd/base"

	[[module.imports]]
		path = "github.com/vyberd/navbar"
	[[module.imports]]
		path = "github.com/vyberd/input"
	[[module.imports]]
		path = "github.com/vyberd/popup"
